using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bibblan_GA
{
    class Library
    {
        public static List<Book> Books = new List<Book>
            {
                new Book("The Great Gatsby", "F. Scott Fitzgerald", "Fiction", 3, 250, true, "The Great Gatsby, F. Scott Fitzgerald's third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted gin was the national drink and sex the national obsession. it is an exquisitely crafted tale of America in the 1920s."),
                new Book("Nineteen Eighty-Four", "George Orwell", "Fiction", 4, 160, true, "Written in 1948, 1984 was George Orwell’s chilling prophecy about the future. And while 1984 has come and gone, his dystopian vision of a government that will do anything to control the narrative is timelier than ever..."),
                new Book("Origin", "Dan Brown", "Fiction", 3, 356, true, "Robert Langdon, Harvard professor of symbology and religious iconology, arrives at the ultramodern Guggenheim Museum Bilbao to attend a major announcement—the unveiling of a discovery that “will change the face of science forever.” The evening’s host is Edmond Kirsch, a forty-year-old billionaire and futurist whose dazzling high-tech inventions and audacious predictions have made him a renowned "),
                new Book("To Kill a Mockingbird", "Harper Lee", "Fiction", 5, 250, true, "Harper Lee's Pulitzer prize-winning masterwork of honor and injustice in the deep south—and the heroism of one man in the face of blind and violent hatred. One of the best - loved stories of all time, To Kill a Mockingbird has been translated into more than forty languages, sold more than forty million copies worldwide, served as the basis for an enormously popular motion picture, and was voted one of the best novels of the twentieth century by librarians across the country.A gripping, heart - wrenching, and wholly remarkable tale of coming - of - age in a South poisoned by virulent prejudice, it views a world of great beauty and savage inequities through the eyes of a young girl, as her father—a crusading local lawyer—risks everything to defend a black man unjustly accused of a terrible crime."),
                new Book("The Martian", "Andy Weir", "Fiction", 2, 124, true, "Now, he’s sure he’ll be the first person to die there. After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he’s alive — and even if he could get word out, his supplies would be gone long before a rescue could arrive. Chances are, though, he won’t have time to starve to death. The damaged machinery, unforgiving environment, or plain-old “human error” are much more likely to kill him first. But Mark isn’t ready to give up yet. Drawing on his ingenuity, his engineering skills — and a relentless, dogged refusal to quit — he steadfastly confronts one seemingly insurmountable obstacle after the next. Will his resourcefulness be enough to overcome the impossible odds against him?"),
                new Book("It", "Stephen King", "Fiction", 5, 223, true, "To the children, the town was their whole world. To the adults, knowing better, Derry, Maine was just their home town: familiar, well-ordered for the most part. A good place to live. It was the children who saw - and felt - what made Derry so horribly different. In the storm drains, in the sewers, IT lurked, taking on the shape of every nightmare, each one's deepest dread. Sometimes IT reached up, seizing, tearing, killing . . . The adults, knowing better, knew nothing. Time passed and the children grew up, moved away. The horror of IT was deep-buried, wrapped in forgetfulness. Until they were called back, once more to confront IT as IT stirred and coiled in the sullen depths of their memories, reaching up again to make their past nightmares a terrible present reality."),
                new Book("The Vegetarian", "Han Kang", "Fiction", 0, 532, false, "Before the nightmare, Yeong-hye and her husband lived an ordinary life. But when splintering, blood-soaked images start haunting her thoughts, Yeong-hye decides to purge her mind and renounce eating meat. In a country where societal mores are strictly obeyed, Yeong-hye's decision to embrace a more “plant-like” existence is a shocking act of subversion. And as her passive rebellion manifests in ever more extreme and frightening forms, scandal, abuse, and estrangement begin to send Yeong-hye spiraling deep into the spaces of her fantasy. In a complete metamorphosis of both mind and body, her now dangerous endeavor will take Yeong-hye—impossibly, ecstatically, tragically—far from her once-known self altogether."),

                new Book("Harry Potter and the Philosophers Stone", "J.K Rowling", "Fantasy", 1, 225, true, "Harry Potter has no idea how famous he is. That's because he's being raised by his miserable aunt and uncle who are terrified Harry will learn that he's really a wizard, just as his parents were. But everything changes when Harry is summoned to attend an infamous school for wizards, and he begins to discover some clues about his illustrious birthright. From the surprising way he is greeted by a lovable giant, to the unique curriculum and colorful faculty at his unusual school, Harry finds himself drawn deep inside a mystical world he never knew existed and closer to his own noble destiny."),
                new Book("Game of Thrones, A song of ice and fire", "George R.R Martin", "Fantasy", 2, 231, true, "From a master of contemporary fantasy comes the first novel of a landmark series unlike any you’ve ever read before. With A Game of Thrones, George R. R. Martin has launched a genuine masterpiece, bringing together the best the genre has to offer. Mystery, intrigue, romance, and adventure fill the pages of this magnificent saga, the first volume in an epic series sure to delight fantasy fans everywhere."),
                new Book("The Hobbit", "J.R.R Tolkien", "Fantasy", 0, 405, false, "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure. They have launched a plot to raid the treasure hoard guarded by Smaug the Magnificent, a large and very dangerous dragon. Bilbo reluctantly joins their quest, unaware that on his journey to the Lonely Mountain he will encounter both a magic ring and a frightening creature known as Gollum."),
                new Book("Sword of Shannara", "Terry Brooks", "Fantasy", 2, 210, true, "Living in peaceful Shady Vale, Shea Ohmsford knew little of the troubles that plagued the rest of the world. Then the giant, forbidding Allanon revaled that the supposedly dead Warlock Lord was plotting to destory the world. The sole weapon against this Power of Darkness was the Sword of Shannara, which could only be used by a true heir of Shannara--Shea being the last of the bloodline, upon whom all hope rested. Soon a Skull Bearer, dread minion of Evil, flew into the Vale, seeking to destroy Shea. To save the Vale, Shea fled, drawing the Skull Bearer after him...."),
                new Book("Oathbringer", "Brandon Sanderson", "Fantasy", 0, 124, false, "In Oathbringer, the third volume of the New York Times bestselling Stormlight Archive, humanity faces a new Desolation with the return of the Voidbringers, a foe with numbers as great as their thirst for vengeance. Dalinar Kholin's Alethi armies won a fleeting victory at a terrible cost: The enemy Parshendi summoned the violent Everstorm, which now sweeps the world with destruction, and in its passing awakens the once peaceful and subservient parshmen to the horror of their millennia-long enslavement by humans. While on a desperate flight to warn his family of the threat, Kaladin Stormblessed must come to grips with the fact that the newly kindled anger of the parshmen may be wholly justified. Nestled in the mountains high above the storms, in the tower city of Urithiru, Shallan Davar investigates the wonders of the ancient stronghold of the Knights Radiant and unearths dark secrets lurking in its depths. And Dalinar realizes that his holy mission to unite his homeland of Alethkar was too narrow in scope. Unless all the nations of Roshar can put aside Dalinar's blood-soaked past and stand together--and unless Dalinar himself can confront that past--even the restoration of the Knights Radiant will not prevent the end of civilization."),
                new Book("The Amber Spyglass", "Philip Pullman", "Fantasy", 0, 215, false, "Brings the intrigue of The Golden Compass and The Subtle Knife to a heart-stopping end, marking the final volume of His Dark Materials as the most powerful of the trilogy. The Amber Spyglass brings the intrigue of The Golden Compass and The Subtle Knife to a heart-stopping end, marking the final volume of His Dark Materials as the most powerful of the trilogy. Along with the return of Lyra, Will, Mrs. Coulter, Lord Asriel, Dr. Mary Malone, and Iorek Byrnison the armored bear, come a host of new characters: the Mulefa, mysterious wheeled creatures with the power to see Dust; Gallivespian Lord Roke, a hand-high spymaster to Lord Asriel; and Metatron, a fierce and mighty angel.So, too, come startling revelations: the painful price Lyra must pay to walk through the land of the dead, the haunting power of Dr.Malone's amber spyglass, and the names of who will live--and who will die--for love. And all the while, war rages with the Kingdom of Heaven, a brutal battle that--in its shocking outcome--will uncover the secret of Dust. Philip Pullman deftly brings the cliff-hangers and mysteries of His Dark Materials to an earthshattering conclusion--and confirms his fantasy trilogy as an undoubted and enduring classic."),

                new Book("Pride and Prejudice", "Jane Austen", "Romance", 0, 250, false, "Few have failed to be charmed by the witty and independent spirit of Elizabeth Bennet in Austen’s beloved classic Pride and Prejudice. When Elizabeth Bennet first meets eligible bachelor Fitzwilliam Darcy, she thinks him arrogant and conceited; he is indifferent to her good looks and lively mind. When she later discovers that Darcy has involved himself in the troubled relationship between his friend Bingley and her beloved sister Jane, she is determined to dislike him more than ever. In the sparkling comedy of manners that follows, Jane Austen shows us the folly of judging by first impressions and superbly evokes the friendships, gossip and snobberies of provincial middle-class life."),
                new Book("Fifty Shades of Grey", "E.L James", "Romance", 0, 250, false, "When literature student Anastasia Steele goes to interview young entrepreneur Christian Grey, she encounters a man who is beautiful, brilliant, and intimidating. The unworldly, innocent Ana is startled to realize she wants this man and, despite his enigmatic reserve, finds she is desperate to get close to him. Unable to resist Ana’s quiet beauty, wit, and independent spirit, Grey admits he wants her, too—but on his own terms."),
                new Book("Wallbanger", "Alice Clayton", "Romance", 3, 250, true, "The first night after Caroline moves into her fantastic new San Francisco apartment, she realizes she's gaining an--um--intimate knowledge of her new neighbor's nocturnal adventures. Thanks to paper-thin walls and the guy's athletic prowess, she can hear not just his bed banging against the wall but the ecstatic response of what seems (as loud night after loud night goes by) like an endless parade of women. And since Caroline is currently on a self-imposed dating hiatus, and her neighbor is clearly lethally attractive to women, she finds her fantasies keep her awake even longer than the noise. So when the wallbanging threatens to literally bounce her out of bed, Caroline, clad in sexual frustration and a pink baby-doll nightie, confronts Simon Parker, her heard-but-never-seen neighbor. The tension between them is as thick as the walls are thin, and the results just as mixed. Suddenly, Caroline is finding she may have discovered a whole new definition of neighborly..."),
                new Book("Twilight", "Stephenie Meyer", "Romance", 3, 250, true, "Isabella Swan's move to Forks, a small, perpetually rainy town in Washington, could have been the most boring move she ever made. But once she meets the mysterious and alluring Edward Cullen, Isabella's life takes a thrilling and terrifying turn. Up until now, Edward has managed to keep his vampire identity a secret in the small community he lives in, but now nobody is safe, especially Isabella, the person Edward holds most dear. The lovers find themselves balanced precariously on the point of a knife-between desire and danger.Deeply romantic and extraordinarily suspenseful, Twilight captures the struggle between defying our instincts and satisfying our desires. This is a love story with bite."),
                new Book("Outlander", "Diana Gabaldon", "Romance", 0, 623, false, "The year is 1945. Claire Randall, a former combat nurse, is just back from the war and reunited with her husband on a second honeymoon when she walks through a standing stone in one of the ancient circles that dot the British Isles. Suddenly she is a Sassenach—an “outlander”—in a Scotland torn by war and raiding border clans in the year of Our Lord...1743. Hurled back in time by forces she cannot understand, Claire is catapulted into the intrigues of lairds and spies that may threaten her life, and shatter her heart. For here James Fraser, a gallant young Scots warrior, shows her a love so absolute that Claire becomes a woman torn between fidelity and desire—and between two vastly different men in two irreconcilable lives."),
                new Book("Emma", "Jane Austen", "Romance", 5, 213, true, "Beautiful, clever, rich - and single - Emma Woodhouse is perfectly content with her life and sees no need for either love or marriage. Nothing, however, delights her more than interfering in the romantic lives of others. But when she ignores the warnings of her good friend Mr. Knightley and attempts to arrange a suitable match for her protegee Harriet Smith, her carefully laid plans soon unravel and have consequences that she never expected. With its imperfect but charming heroine and its witty and subtle exploration of relationships, Emma is often seen as Jane Austen's most flawless work."),

                new Book("Steve Jobs", "Walter Isaacson", "Biography", 0, 250, false, "Based on more than forty interviews with Steve Jobs conducted over two years—as well as interviews with more than 100 family members, friends, adversaries, competitors, and colleagues—Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries: personal computers, animated movies, music, phones, tablet computing, and digital publishing. Isaacson’s portrait touched millions of readers."),
                new Book("The Diary of Anne Frank", "Anne Frank", "Biography", 3, 250, true, "In 1942, with the Nazis occupying Holland, a thirteen-year-old Jewish girl and her family fled their home in Amsterdam and went into hiding. For the next two years, until their whereabouts were betrayed to the Gestapo, the Franks and another family lived cloistered in the “Secret Annexe” of an old office building. Cut off from the outside world, they faced hunger, boredom, the constant cruelties of living in confined quarters, and the ever-present threat of discovery and death. In her diary Anne Frank recorded vivid impressions of her experiences during this period. By turns thoughtful, moving, and surprisingly humorous, her account offers a fascinating commentary on human courage and frailty and a compelling self-portrait of a sensitive and spirited young woman whose promise was tragically cut short."),
                new Book("Dreams from My Father", "Barack Obama", "Biography", 0, 250, false, "In this lyrical, unsentimental, and compelling memoir, the son of a black African father and a white American mother searches for a workable meaning to his life as a black American. It begins in New York, where Barack Obama learns that his father—a figure he knows more as a myth than as a man—has been killed in a car accident. This sudden death inspires an emotional odyssey—first to a small town in Kansas, from which he retraces the migration of his mother’s family to Hawaii, and then to Kenya, where he meets the African side of his family, confronts the bitter truth of his father’s life, and at last reconciles his divided inheritance. "),
                new Book("What Happened", "Hillary Clinton", "Biography", 4, 353, true, "For the first time, Hillary Rodham Clinton reveals what she was thinking and feeling during one of the most controversial and unpredictable presidential elections in history. Now free from the constraints of running, Hillary takes you inside the intense personal experience of becoming the first woman nominated for president by a major party in an election marked by rage, sexism, exhilarating highs and infuriating lows, stranger-than-fiction twists, Russian interference, and an opponent who broke all the rules. This is her most personal memoir yet. In these pages, she describes what it was like to run against Donald Trump, the mistakes she made, how she has coped with a shocking and devastating loss, and how she found the strength to pick herself back up afterward. With humor and candor, she tells readers what it took to get back on her feet—the rituals, relationships, and reading that got her through, and what the experience has taught her about life. She speaks about the challenges of being a strong woman in the public eye, the criticism over her voice, age, and appearance, and the double standard confronting women in politics. She lays out how the 2016 election was marked by an unprecedented assault on our democracy by a foreign adversary.By analyzing the evidence and connecting the dots, Hillary shows just how dangerous the forces are that shaped the outcome, and why Americans need to understand them to protect our values and our democracy in the future. The election of 2016 was unprecedented and historic. What Happened is the story of that campaign and its aftermath—both a deeply intimate account and a cautionary tale for the nation."),
                new Book("Crippled America: How to Make America Great Again", "Donald J. Trump", "Biography", 7, 421, true, "It’s time to bring America back to its rightful owners—the American people. I’m not going to play the same game politicians have been playing for decades—all talk, no action, while special interests and lobbyists dictate our laws. I am shaking up the establishment on both sides of the political aisle because I can’t be bought. I want to bring America back, to make it great and prosperous again, and to be sure we are respected by our allies and feared by our adversaries. It’s time for action. Americans are fed up with politics as usual. And they should be! In this book, I outline my vision to make America great again, including: how to fix our failing economy; how to reform health care so it is more efficient, cost-effective, and doesn’t alienate both doctors and patients; how to rebuild our military and start winning wars—instead of watching our enemies take over—while keeping our promises to our great veterans; how to ensure that our education system offers the resources that allow our students to compete internationally, so tomorrow’s jobseekers have the tools they need to succeed; and how to immediately bring jobs back to America by closing our doors to illegal immigrants, and pressuring businesses to produce their goods at home. This book is my blueprint for how to Make America Great Again. It’s not hard.We just need someone with the courage to say what needs to be said."),
                new Book("Finding My Virginity", "Richard Branson", "Biography", 3, 250, true, "Richard Branson’s Losing My Virginity shared the outrageous tale of how he built Virgin from a student magazine into one of the greatest brands in history. No challenge was too daunting, no opportunity too outlandish to pursue. And each new adventure started with five simple words: “Screw it, let’s do it.”")
        };
}
    }

